setwd("C:/My Stuff/Semester 3/Data Mining/TB Data Mining")
getwd()
install.packages("C50")
install.packages("printr")
library(C50)
library(printr)
dataset <- read.csv("1.csv", sep = ";")
dataset$brand<-as.factor(dataset$brand)
model <- C5.0(brand ~., data=dataset)
summary(model)
plot(model)
datatesting <- dataset[,1:5]
predictions <- predict(model, dataset)
table(predictions, dataset$brand)